version: '3'
services: 
    graphql:
        container_name: graphql
        build: .
        ports:
            - "5000:5000"
        volumes: 
            - "./:/app"
        links: 
            - postgres
        depends_on: 
            - postgres
        restart: always
    
    postgres:
        container_name: postgres
        image: postgres
        environment: 
            POSTGRES_USER: root
            POSTGRES_PASSWORD: eventio
            POSTGRES_DATABASE: eventio
        restart: always