version: '3'
services: 
    eventio:
        container_name: eventio_graphql
        build: .
        ports:
            - "5000:5000"
        volumes: 
            - ./:/app
        links: 
            - postgres
        depends_on: 
            - postgres
        restart: always
    
    postgres:
        container_name: eventio_postgres
        image: postgres
        environment: 
            POSTGRES_USER: root
            POSTGRES_PASSWORD: eventio
        volumes: 
            - ./docker/init/db.sh:/docker-entrypoint-initdb.d/initdb.sh # stekaje ode
            - ./docker/postgres:/var/lib/postgresql/data

        restart: always